### PR TITLE
fixing bug where the time series plots weren't displaying correctly.

### PR DESCRIPTION
**Pull request by bstephens82**

### CODE REVIEW

**Comment by vlarson** [comment]
Would now be a good time to merge your new plots with @zhunguo's version of diagnostic_v2_0?  He has generalized his code so that output from either CAM or E3SM can be handled by changing some flag settings:

https://github.com/larson-group/e3sm/commit/c77ace1622c12f49b32f593e0346b4ba6f9bc4e3#diff-8f51372feda90931f46891cd64261dbbc5f4ecac53dd072a695cf8ba683380c1R485

**Comment by vlarson** [comment]
On 10 Oct 2024, @zhunguo wrote

"In the commit [c77ace1](https://github.com/larson-group/e3sm/commit/c77ace1622c12f49b32f593e0346b4ba6f9bc4e3), there variables are added in main code CLUBB_PROF_20240831.py and  function_cal_mean.py

affl=  eam or cam or whatever

suffix =['h0','h0a','h0’]

mapfile = [\
'/data/zhun/inputdata/[map_ne30pg2_to_cmip6_180x360_aave.20200201.nc](http://map_ne30pg2_to_cmip6_180x360_aave.20200201.nc/)',\
'/data/zhun/inputdata/lnd/clm2/mappingdata/maps/ne30pg3/[map_ne30pg3_to_0.5x0.5_nomask_aave_da_c180515.nc](http://map_ne30pg3_to_0.5x0.5_nomask_aave_da_c180515.nc/)',\
'/data/zhun/inputdata/lnd/clm2/mappingdata/maps/ne30pg3/[map_ne30pg3_to_0.5x0.5_nomask_aave_da_c180515.nc](http://map_ne30pg3_to_0.5x0.5_nomask_aave_da_c180515.nc/)',\
]

The CESM mapfile, I only found for 0.5 degrees, causing it to be slow when running E3SM_diag.

I use a combination of these three variables to get cesm and E3SM in various output formats running at the same time.
Regarding the filepath and output directory, I am defaulting to output directly in the same directory, outfile=filepath[im]+cases[im]+'/'.
Maybe it has something to do with the way I store it, it's working fine so far. I wonder if that's why it won't run on Derecho.

The current code also has a shortcoming, the NCO paths are not flexible enough. 

For example
···
 ncea_str ='/public/software/apps/nco-4.8.1/intel/bin//ncea '
 ncwa_str ='/public/software/apps/nco-4.8.1/intel/bin//ncwa -C '
 ncks_str ='/public/software/apps/nco-4.8.1/intel/bin//ncks '
 ncap2_str ='/public/software/apps/nco-4.8.1/intel/bin//ncap2 '
 ncrcat_str ='/public/software/apps/nco-4.8.1/intel/bin//ncrcat '
 ncrename_str = '/public/software/apps/nco-4.8.1/intel/bin//ncrename '
···
This really isn't a smart way, and it's really only necessary to declare them once. Maybe I should extract them and put them in interfaces."

**Comment by vlarson** [comment]
On 11 Oct 2024, @bstephens82 emailed:

"This morning I've been working on getting the latest version of the E3SM diagnostics working on Casper (same environment as Derecho).  Here are the things I've run into so far. 

(Also, per Zhun's last email, I've started using the CLUBB_PROF_ 20240831.py file as my main file.)

Steps to get new e3sm repo working with my data.

Basic changes to be expected:

In main file, change case, outdir, filepath, cases, years, nyear, affl, suffix, mapfile, list_of_parameters

In main file, change filepathobs to my local copy of Zhun’s obs files

Problematic changes:

Missing package:

The code first complains because there is no “draw_daynight_low.py” script found anywhere, which the code is trying to import, so I commented out all of these lines including the “drawnight” logical

function_cal_mean problems

The code then complains because of the paths in function_cal_mean.py.  This is because the “climo” folder doesn’t exist, because the code tries to create the climo file in a place that doesn’t exist, namely the “run” directory which is not the typical place to look on Derecho since CAM files are archived in a different place.  In other words, the “filepath” I gave which is where the output files are stored is different from where it wants to create the climo directory.  So I need to go through and replace “run/climo” with “atm/hist/climo”.  I also ended up commenting a number of other lines out because they would also require path updates but as far as I can tell they are not used in what I want to do.

I also prefer for the standard “climo” netcdf files to be created within the newly created “climo” directory.  I have to change the paths for the variable “outfile” in order to accomplish this.

Next error is it doesn’t recognize the paths to the NCO operators. On Derecho/Casper, what I do is load the NCO package, and then just replace the unrecognized paths with normal NCO commands.  This could be fixed with a switch (which could be automated) based on the computing environment.

Next error is for some reason two of the seasonal climo files are regridded but the other two are not, so when it goes to regrid the ANN file, it’s being fed two unstructured files and two regridded files.  I have no idea how/if this works for Zhun, but it crashes for me.  So I had to comment out the lines where the two previous unstructured seasonal files are regridded.

function_pick_out.py problems

To use function_pick_out.py, need to add and define “fv”, which I’m setting to false for now since I have unstructured output I can use.

In CLUBB_PROF_XXXX.py, add “fv” (=False) to the list of variables going into function_pick_out.pick_out()

Paths will also need to be updated here since Derecho and Casper place the files in different locations than where they end up on Zhun’s environment I assume.

I tried setting pickout=False just to see if I could get past these errors by turning this whole thing off, I’ll try again later…

draw_plots_hoz_2D.py

Paths need to be updated because it can’t find the files…"

**Comment by vlarson** [comment]
On 12 Oct 2024, @zhunguo emailed:

"I remember Kate did a version that included the fv flag. the introduction of the FV flag allowed for more flexibility in function_pick_out.py. That version also had the flexibility to specify the path to the hist file. Since I've been doing it under E3SM and she had to store her changes in another brach, I haven't merged her changes in the source program under E3SM for now. Later I need to merge Kate's version, which would greatly increase the freedom of the software.

The climo directory is used to store the hist files (ANN, DJF, and JJA) after remap, and the subroutine cal_mean automatically generates the climo directory in the $case/run directory. The setting of $case/run is not flexible in my version. If $case/run doesn't exist, the climo directory may not be generated either. Wouldn't it be more appropriate to make them adjustable variables? Do you have a better idea?

I've made some updates today. https://github.com/larson-group/e3sm/commit/62430ec3b8b6ccee2e7e31dd777c84c3ee5485d1
the NCO can be freely specified, as well as the new RG_OBS generation code, maybe we can try this version. It doesn't matter  without the FV flag, if you are using SE too. As for the night-day module, it's perfectly fine to comment it out for the time being, as there's a bit of modification to be done to CESM with it as well."

**Review by Katetc — APPROVED** [review]
This looks very useful!

**Pull request merged**
